# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\computer\PycharmProjects\UIProjects\info_manage.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(586, 476)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imgs/Desktop/SMS/resource/window_icon/1208251.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget.addItem(item)
        self.horizontalLayout_2.addWidget(self.listWidget)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_0 = QtWidgets.QWidget()
        self.page_0.setObjectName("page_0")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.page_0)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.page_0)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.page_0)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_26 = QtWidgets.QLabel(self.page_0)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 6, 2, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.page_0)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_3, 6, 3, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.page_0)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 3, 1, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.page_0)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_2.addWidget(self.lineEdit_5, 3, 3, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.page_0)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.page_0)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.page_0)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.page_0)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 5, 2, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.page_0)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_2.addWidget(self.lineEdit_6, 4, 1, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.page_0)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_2.addWidget(self.lineEdit_7, 4, 3, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.page_0)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_2.addWidget(self.lineEdit_8, 5, 1, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.page_0)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_2.addWidget(self.lineEdit_9, 5, 3, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page_0)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.page_0)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 6, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.page_0)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_2.addWidget(self.lineEdit_11, 8, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.page_0)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 8, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.page_0)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 0, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.page_0)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_2.addWidget(self.lineEdit_10, 6, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.page_0)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.page_0)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 2, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.page_0)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 7, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.page_0)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 7, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.page_0)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 2, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.page_0)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.page_0)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.page_0)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 4, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.page_0)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 3, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.page_0)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 9, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.page_0)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 3, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.page_0)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 9, 2, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.page_0)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout_2.addWidget(self.lineEdit_21, 1, 1, 1, 1)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.page_0)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout_2.addWidget(self.lineEdit_22, 1, 3, 1, 1)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.page_0)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout_2.addWidget(self.lineEdit_23, 2, 1, 1, 1)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.page_0)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.gridLayout_2.addWidget(self.lineEdit_24, 2, 3, 1, 1)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.page_0)
        self.lineEdit_25.setReadOnly(True)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout_2.addWidget(self.lineEdit_25, 7, 1, 1, 1)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.page_0)
        self.lineEdit_26.setReadOnly(True)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.gridLayout_2.addWidget(self.lineEdit_26, 7, 3, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.page_0)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 9, 1, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.page_0)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_2.addWidget(self.pushButton_13, 9, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 3)
        self.stackedWidget.addWidget(self.page_0)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_4.addWidget(self.lineEdit_12)
        self.pushButton_5 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_4.addWidget(self.pushButton_5)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 3)
        self.horizontalLayout_4.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_3.addWidget(self.lineEdit_13, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.page_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 2, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_3.addWidget(self.lineEdit_15, 0, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.page_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 1, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.page_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 2, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.page_2)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_4, 2, 1, 1, 1)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_27.setReadOnly(True)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.gridLayout_3.addWidget(self.lineEdit_27, 1, 1, 1, 1)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_28.setReadOnly(True)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.gridLayout_3.addWidget(self.lineEdit_28, 1, 3, 1, 1)
        self.gridLayout_3.setRowStretch(0, 1)
        self.gridLayout_3.setRowStretch(1, 1)
        self.gridLayout_3.setRowStretch(2, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_14 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_5.addWidget(self.pushButton_14)
        self.pushButton_6 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_5.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_5.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_5.addWidget(self.pushButton_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 3)
        self.verticalLayout_2.setStretch(2, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_19 = QtWidgets.QLabel(self.page_3)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_3.addWidget(self.label_19)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.horizontalLayout_3.addWidget(self.lineEdit_14)
        self.pushButton_9 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_3.addWidget(self.pushButton_9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_19.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout.addWidget(self.lineEdit_19, 1, 3, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.page_3)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 0, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.page_3)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 1, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.page_3)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 2, 0, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout.addWidget(self.lineEdit_17, 0, 3, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout.addWidget(self.lineEdit_16, 0, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.page_3)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 0, 2, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout.addWidget(self.lineEdit_18, 1, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.page_3)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 1, 2, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.page_3)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 3, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.page_3)
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 3, 2, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout.addWidget(self.lineEdit_20, 2, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.page_3)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 2, 2, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.page_3)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout.addWidget(self.comboBox_5, 3, 3, 1, 1)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_29.setReadOnly(True)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.gridLayout.addWidget(self.lineEdit_29, 3, 1, 1, 1)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_30.setReadOnly(True)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.gridLayout.addWidget(self.lineEdit_30, 2, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_15 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_6.addWidget(self.pushButton_15)
        self.pushButton_10 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_6.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_6.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_6.addWidget(self.pushButton_12)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 4)
        self.verticalLayout_3.setStretch(2, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget.addWidget(self.page_4)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 586, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menuBar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menuBar)
        self.menu_5.setObjectName("menu_5")
        MainWindow.setMenuBar(self.menuBar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())
        self.menuBar.addAction(self.menu_4.menuAction())
        self.menuBar.addAction(self.menu_5.menuAction())

        self.retranslateUi(MainWindow)
        self.listWidget.setCurrentRow(0)
        self.stackedWidget.setCurrentIndex(2)
        self.listWidget.currentRowChanged['int'].connect(self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.lineEdit_2)
        MainWindow.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        MainWindow.setTabOrder(self.lineEdit_3, self.lineEdit_21)
        MainWindow.setTabOrder(self.lineEdit_21, self.lineEdit_22)
        MainWindow.setTabOrder(self.lineEdit_22, self.lineEdit_23)
        MainWindow.setTabOrder(self.lineEdit_23, self.lineEdit_24)
        MainWindow.setTabOrder(self.lineEdit_24, self.lineEdit_4)
        MainWindow.setTabOrder(self.lineEdit_4, self.lineEdit_5)
        MainWindow.setTabOrder(self.lineEdit_5, self.lineEdit_6)
        MainWindow.setTabOrder(self.lineEdit_6, self.lineEdit_7)
        MainWindow.setTabOrder(self.lineEdit_7, self.lineEdit_8)
        MainWindow.setTabOrder(self.lineEdit_8, self.lineEdit_9)
        MainWindow.setTabOrder(self.lineEdit_9, self.lineEdit_10)
        MainWindow.setTabOrder(self.lineEdit_10, self.comboBox_3)
        MainWindow.setTabOrder(self.comboBox_3, self.lineEdit_25)
        MainWindow.setTabOrder(self.lineEdit_25, self.lineEdit_26)
        MainWindow.setTabOrder(self.lineEdit_26, self.lineEdit_11)
        MainWindow.setTabOrder(self.lineEdit_11, self.pushButton_13)
        MainWindow.setTabOrder(self.pushButton_13, self.pushButton_4)
        MainWindow.setTabOrder(self.pushButton_4, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.lineEdit_12)
        MainWindow.setTabOrder(self.lineEdit_12, self.pushButton_5)
        MainWindow.setTabOrder(self.pushButton_5, self.lineEdit_13)
        MainWindow.setTabOrder(self.lineEdit_13, self.lineEdit_15)
        MainWindow.setTabOrder(self.lineEdit_15, self.lineEdit_27)
        MainWindow.setTabOrder(self.lineEdit_27, self.lineEdit_28)
        MainWindow.setTabOrder(self.lineEdit_28, self.comboBox_4)
        MainWindow.setTabOrder(self.comboBox_4, self.pushButton_14)
        MainWindow.setTabOrder(self.pushButton_14, self.pushButton_6)
        MainWindow.setTabOrder(self.pushButton_6, self.pushButton_7)
        MainWindow.setTabOrder(self.pushButton_7, self.pushButton_8)
        MainWindow.setTabOrder(self.pushButton_8, self.lineEdit_14)
        MainWindow.setTabOrder(self.lineEdit_14, self.pushButton_9)
        MainWindow.setTabOrder(self.pushButton_9, self.lineEdit_16)
        MainWindow.setTabOrder(self.lineEdit_16, self.lineEdit_17)
        MainWindow.setTabOrder(self.lineEdit_17, self.lineEdit_18)
        MainWindow.setTabOrder(self.lineEdit_18, self.lineEdit_19)
        MainWindow.setTabOrder(self.lineEdit_19, self.lineEdit_20)
        MainWindow.setTabOrder(self.lineEdit_20, self.lineEdit_30)
        MainWindow.setTabOrder(self.lineEdit_30, self.lineEdit_29)
        MainWindow.setTabOrder(self.lineEdit_29, self.comboBox_5)
        MainWindow.setTabOrder(self.comboBox_5, self.pushButton_15)
        MainWindow.setTabOrder(self.pushButton_15, self.pushButton_10)
        MainWindow.setTabOrder(self.pushButton_10, self.pushButton_11)
        MainWindow.setTabOrder(self.pushButton_11, self.pushButton_12)
        MainWindow.setTabOrder(self.pushButton_12, self.listWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "信息管理界面"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "员工管理"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "部门管理"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "职位管理"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "用户管理"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "签到管理"))
        item = self.listWidget.item(5)
        item.setText(_translate("MainWindow", "请假管理"))
        item = self.listWidget.item(6)
        item.setText(_translate("MainWindow", "公告管理"))
        item = self.listWidget.item(7)
        item.setText(_translate("MainWindow", "留言管理"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "员工ID:"))
        self.pushButton.setText(_translate("MainWindow", "查找"))
        self.label_26.setText(_translate("MainWindow", "状态："))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "离职"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "在职"))
        self.label_4.setText(_translate("MainWindow", "姓名："))
        self.label_6.setText(_translate("MainWindow", "职位ID："))
        self.label_8.setText(_translate("MainWindow", "部门ID："))
        self.label_24.setText(_translate("MainWindow", "部门名称："))
        self.label_27.setText(_translate("MainWindow", "登录密码："))
        self.label_10.setText(_translate("MainWindow", "性别："))
        self.label_12.setText(_translate("MainWindow", "学历："))
        self.label_18.setText(_translate("MainWindow", "出生日期："))
        self.label_14.setText(_translate("MainWindow", "创建时间："))
        self.label_16.setText(_translate("MainWindow", "修改时间："))
        self.label_20.setText(_translate("MainWindow", "入职日期："))
        self.label_21.setText(_translate("MainWindow", "爱好："))
        self.label_2.setText(_translate("MainWindow", "员工ID："))
        self.label_22.setText(_translate("MainWindow", "薪金："))
        self.label_15.setText(_translate("MainWindow", "家庭住址："))
        self.pushButton_2.setText(_translate("MainWindow", "更新"))
        self.label_11.setText(_translate("MainWindow", "联系方式："))
        self.pushButton_3.setText(_translate("MainWindow", "删除"))
        self.lineEdit_23.setInputMask(_translate("MainWindow", "0000-00-00;_"))
        self.lineEdit_24.setInputMask(_translate("MainWindow", "0000-00-00;_"))
        self.lineEdit_25.setInputMask(_translate("MainWindow", "0000-00-00 00:00:00;_"))
        self.lineEdit_26.setInputMask(_translate("MainWindow", "0000-00-00 00:00:00;_"))
        self.pushButton_4.setText(_translate("MainWindow", "添加"))
        self.pushButton_13.setText(_translate("MainWindow", "清空"))
        self.label_3.setText(_translate("MainWindow", "部门ID："))
        self.pushButton_5.setText(_translate("MainWindow", "查找"))
        self.label_5.setText(_translate("MainWindow", "部门ID："))
        self.label_7.setText(_translate("MainWindow", "记录创建时间："))
        self.label_9.setText(_translate("MainWindow", "部门名称："))
        self.label_13.setText(_translate("MainWindow", "最后修改时间："))
        self.label_17.setText(_translate("MainWindow", "状态："))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "不存在"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "存在"))
        self.lineEdit_27.setInputMask(_translate("MainWindow", "0000-00-00 00:00:00;_"))
        self.lineEdit_28.setInputMask(_translate("MainWindow", "0000-00-00 00:00:00;_"))
        self.pushButton_14.setText(_translate("MainWindow", "清空"))
        self.pushButton_6.setText(_translate("MainWindow", "添加"))
        self.pushButton_7.setText(_translate("MainWindow", "删除"))
        self.pushButton_8.setText(_translate("MainWindow", "更新"))
        self.label_19.setText(_translate("MainWindow", "职位ID："))
        self.pushButton_9.setText(_translate("MainWindow", "查找"))
        self.label_23.setText(_translate("MainWindow", "职位ID："))
        self.label_28.setText(_translate("MainWindow", "职位名称："))
        self.label_30.setText(_translate("MainWindow", "管理人："))
        self.label_25.setText(_translate("MainWindow", "所在部门ID："))
        self.label_29.setText(_translate("MainWindow", "职位人数："))
        self.label_32.setText(_translate("MainWindow", "最后修改时间："))
        self.label_33.setText(_translate("MainWindow", "状态："))
        self.label_31.setText(_translate("MainWindow", "创建时间："))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "不存在"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "存在"))
        self.lineEdit_29.setInputMask(_translate("MainWindow", "0000-00-00 00:00:00;_"))
        self.lineEdit_30.setInputMask(_translate("MainWindow", "0000-00-00 00:00:00;_"))
        self.pushButton_15.setText(_translate("MainWindow", "清空"))
        self.pushButton_10.setText(_translate("MainWindow", "添加"))
        self.pushButton_11.setText(_translate("MainWindow", "删除"))
        self.pushButton_12.setText(_translate("MainWindow", "更新"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑"))
        self.menu_3.setTitle(_translate("MainWindow", "查看"))
        self.menu_4.setTitle(_translate("MainWindow", "工具"))
        self.menu_5.setTitle(_translate("MainWindow", "帮助"))
        self.action.setText(_translate("MainWindow", "另存为"))
        self.action_2.setText(_translate("MainWindow", "退出"))

import SMS_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

